// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;

namespace McpBridge.Execution;

public static class McpGeneratedTools
{
	public class StaticallyBoundTool
	{
		public string Name { get; set; }
		public string Description { get; set; }
		public string Group { get; set; }
		public bool ReadOnlyHint { get; set; }
		public bool DestructiveHint { get; set; }
		public Func<JsonElement, object> Invoke { get; set; }
	}

	public static readonly Dictionary<string, StaticallyBoundTool> Tools = new()
	{
		["sbox_anim_set_param"] = new StaticallyBoundTool
		{
			Name = "sbox_anim_set_param",
			Description = "Sets an AnimGraph parameter on a ModelRenderer. Supports float, bool, int, and trigger.",
			Group = "Animation",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.AnimationTools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("paramName", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				var p2 = el.TryGetProperty("value", out var v2) ? JsonSerializer.Deserialize<string>(v2.GetRawText()) : default(string);
				var p3 = el.TryGetProperty("paramType", out var v3) ? JsonSerializer.Deserialize<string>(v3.GetRawText()) : default(string);
				return inst.SetAnimParam(p0, p1, p2, p3);
			}
		},
		["sbox_anim_get_params"] = new StaticallyBoundTool
		{
			Name = "sbox_anim_get_params",
			Description = "Gets all readable AnimGraph parameters from a ModelRenderer or SkinnedModelRenderer.",
			Group = "Animation",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.AnimationTools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.GetAnimParams(p0);
			}
		},
		["sbox_anim_play_sequence"] = new StaticallyBoundTool
		{
			Name = "sbox_anim_play_sequence",
			Description = "Plays an animation sequence on a ModelRenderer by name.",
			Group = "Animation",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.AnimationTools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("sequenceName", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				var p2 = el.TryGetProperty("loop", out var v2) ? JsonSerializer.Deserialize<bool>(v2.GetRawText()) : default(bool);
				return inst.PlaySequence(p0, p1, p2);
			}
		},
		["sbox_anim_list_sequences"] = new StaticallyBoundTool
		{
			Name = "sbox_anim_list_sequences",
			Description = "Lists all animation sequences on a ModelRenderer.",
			Group = "Animation",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.AnimationTools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.ListSequences(p0);
			}
		},
		["sbox_anim_set_layer_weight"] = new StaticallyBoundTool
		{
			Name = "sbox_anim_set_layer_weight",
			Description = "Sets the blend weight (0-1) for an animation layer on a ModelRenderer.",
			Group = "Animation",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.AnimationTools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("layerIndex", out var v1) ? JsonSerializer.Deserialize<int>(v1.GetRawText()) : default(int);
				var p2 = el.TryGetProperty("weight", out var v2) ? JsonSerializer.Deserialize<float>(v2.GetRawText()) : default(float);
				return inst.SetLayerWeight(p0, p1, p2);
			}
		},
		["sbox_anim_trigger"] = new StaticallyBoundTool
		{
			Name = "sbox_anim_trigger",
			Description = "Triggers an AnimGraph event by name on a ModelRenderer.",
			Group = "Animation",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.AnimationTools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("eventName", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				return inst.AnimTrigger(p0, p1);
			}
		},
		["sbox_asset_save_prefab"] = new StaticallyBoundTool
		{
			Name = "sbox_asset_save_prefab",
			Description = "Saves a GameObject as a prefab file.",
			Group = "Asset",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.AssetTools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("fileName", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				return inst.SavePrefab(p0, p1);
			}
		},
		["sbox_asset_load_prefab"] = new StaticallyBoundTool
		{
			Name = "sbox_asset_load_prefab",
			Description = "Spawns a prefab file into the scene at a position.",
			Group = "Asset",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.AssetTools();
				var p0 = el.TryGetProperty("prefabPath", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("x", out var v1) ? JsonSerializer.Deserialize<float>(v1.GetRawText()) : default(float);
				var p2 = el.TryGetProperty("y", out var v2) ? JsonSerializer.Deserialize<float>(v2.GetRawText()) : default(float);
				var p3 = el.TryGetProperty("z", out var v3) ? JsonSerializer.Deserialize<float>(v3.GetRawText()) : default(float);
				var p4 = el.TryGetProperty("useQueue", out var v4) ? JsonSerializer.Deserialize<bool>(v4.GetRawText()) : default(bool);
				return inst.LoadPrefab(p0, p1, p2, p3, p4);
			}
		},
		["sbox_asset_info"] = new StaticallyBoundTool
		{
			Name = "sbox_asset_info",
			Description = "Returns metadata about an asset file.",
			Group = "Asset",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.AssetTools();
				var p0 = el.TryGetProperty("path", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.AssetInfo(p0);
			}
		},
		["sbox_asset_duplicate"] = new StaticallyBoundTool
		{
			Name = "sbox_asset_duplicate",
			Description = "Duplicates a GameObject in the scene (deep clone).",
			Group = "Asset",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.AssetTools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.DuplicateObject(p0);
			}
		},
		["sbox_asset_find_missing"] = new StaticallyBoundTool
		{
			Name = "sbox_asset_find_missing",
			Description = "Scans all GameObjects for components with null/missing references.",
			Group = "Asset",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.AssetTools();
				return inst.FindMissingReferences();
			}
		},
		["sbox_asset_bulk_import"] = new StaticallyBoundTool
		{
			Name = "sbox_asset_bulk_import",
			Description = "Imports multiple prefabs from a JSON array. Each entry: { path, x?, y?, z? }",
			Group = "Asset",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.AssetTools();
				var p0 = el.TryGetProperty("entries", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.BulkImport(p0);
			}
		},
		["sbox_asset_export_json"] = new StaticallyBoundTool
		{
			Name = "sbox_asset_export_json",
			Description = "Exports a GameObject and its children to JSON.",
			Group = "Asset",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.AssetTools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.ExportJson(p0);
			}
		},
		["sbox_asset_import_json"] = new StaticallyBoundTool
		{
			Name = "sbox_asset_import_json",
			Description = "Imports a GameObject hierarchy from a JSON string. Recreates child GameObjects, attaches components, and parses properties.",
			Group = "Asset",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.AssetTools();
				var p0 = el.TryGetProperty("json", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("parentGuidStr", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				return inst.ImportJson(p0, p1);
			}
		},
		["sbox_generate_asset"] = new StaticallyBoundTool
		{
			Name = "sbox_generate_asset",
			Description = "Procedurally generates wav audio or bmp texture assets and writes them atomically to the project directories to prevent IO kilitlenmeleri.",
			Group = "Asset",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.AssetTools();
				var p0 = el.TryGetProperty("path", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("type", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				var p2 = el.TryGetProperty("waveType", out var v2) ? JsonSerializer.Deserialize<string>(v2.GetRawText()) : default(string);
				var p3 = el.TryGetProperty("frequency", out var v3) ? JsonSerializer.Deserialize<float>(v3.GetRawText()) : default(float);
				var p4 = el.TryGetProperty("duration", out var v4) ? JsonSerializer.Deserialize<float>(v4.GetRawText()) : default(float);
				var p5 = el.TryGetProperty("pattern", out var v5) ? JsonSerializer.Deserialize<string>(v5.GetRawText()) : default(string);
				var p6 = el.TryGetProperty("width", out var v6) ? JsonSerializer.Deserialize<int>(v6.GetRawText()) : default(int);
				var p7 = el.TryGetProperty("height", out var v7) ? JsonSerializer.Deserialize<int>(v7.GetRawText()) : default(int);
				var p8 = el.TryGetProperty("colorHex", out var v8) ? JsonSerializer.Deserialize<string>(v8.GetRawText()) : default(string);
				return inst.GenerateAsset(p0, p1, p2, p3, p4, p5, p6, p7, p8);
			}
		},
		["sbox_run_command"] = new StaticallyBoundTool
		{
			Name = "sbox_run_command",
			Description = "Executes a console command in the S&box engine.",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				var p0 = el.TryGetProperty("command", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.RunCommand(p0);
			}
		},
		["sbox_get_object_details"] = new StaticallyBoundTool
		{
			Name = "sbox_get_object_details",
			Description = "Returns detailed information about a specific GameObject.",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.GetObjectDetails(p0);
			}
		},
		["sbox_list_assets"] = new StaticallyBoundTool
		{
			Name = "sbox_list_assets",
			Description = "Lists project assets by type.",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				var p0 = el.TryGetProperty("assetType", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.ListAssets(p0);
			}
		},
		["sbox_get_property"] = new StaticallyBoundTool
		{
			Name = "sbox_get_property",
			Description = "Reads a property value from a component on a GameObject.",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("componentType", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				var p2 = el.TryGetProperty("propertyName", out var v2) ? JsonSerializer.Deserialize<string>(v2.GetRawText()) : default(string);
				return inst.GetProperty(p0, p1, p2);
			}
		},
		["sbox_set_property"] = new StaticallyBoundTool
		{
			Name = "sbox_set_property",
			Description = "Sets a component property by name. Value is parsed to the correct type automatically.",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("componentType", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				var p2 = el.TryGetProperty("propertyName", out var v2) ? JsonSerializer.Deserialize<string>(v2.GetRawText()) : default(string);
				var p3 = el.TryGetProperty("value", out var v3) ? JsonSerializer.Deserialize<string>(v3.GetRawText()) : default(string);
				return inst.SetProperty(p0, p1, p2, p3);
			}
		},
		["sbox_remove_component"] = new StaticallyBoundTool
		{
			Name = "sbox_remove_component",
			Description = "Removes a component from a GameObject.",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("componentType", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				return inst.RemoveComponent(p0, p1);
			}
		},
		["sbox_set_component_enabled"] = new StaticallyBoundTool
		{
			Name = "sbox_set_component_enabled",
			Description = "Enables or disables a component on a GameObject.",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("componentType", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				var p2 = el.TryGetProperty("enabled", out var v2) ? JsonSerializer.Deserialize<string>(v2.GetRawText()) : default(string);
				return inst.SetComponentEnabled(p0, p1, p2);
			}
		},
		["sbox_list_components"] = new StaticallyBoundTool
		{
			Name = "sbox_list_components",
			Description = "Lists all available component types.",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				var p0 = el.TryGetProperty("filter", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.ListComponents(p0);
			}
		},
		["sbox_duplicate_object"] = new StaticallyBoundTool
		{
			Name = "sbox_duplicate_object",
			Description = "Duplicates a GameObject.",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("newName", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				var p2 = el.TryGetProperty("offsetX", out var v2) ? JsonSerializer.Deserialize<float>(v2.GetRawText()) : default(float);
				var p3 = el.TryGetProperty("offsetY", out var v3) ? JsonSerializer.Deserialize<float>(v3.GetRawText()) : default(float);
				var p4 = el.TryGetProperty("offsetZ", out var v4) ? JsonSerializer.Deserialize<float>(v4.GetRawText()) : default(float);
				return inst.DuplicateObject(p0, p1, p2, p3, p4);
			}
		},
		["sbox_set_parent"] = new StaticallyBoundTool
		{
			Name = "sbox_set_parent",
			Description = "Changes the parent of a GameObject.",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				var p0 = el.TryGetProperty("childGuidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("parentGuidStr", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				return inst.SetParent(p0, p1);
			}
		},
		["sbox_run_sequence"] = new StaticallyBoundTool
		{
			Name = "sbox_run_sequence",
			Description = "Execute multiple tools in sequence. Steps is JSON array of { tool, params } objects.",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				var p0 = el.TryGetProperty("steps", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.RunSequence(p0);
			}
		},
		["sbox_run_batch"] = new StaticallyBoundTool
		{
			Name = "sbox_run_batch",
			Description = "Execute multiple tools sequentially. All steps run regardless of errors. Steps is JSON array of { tool, params }.",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				var p0 = el.TryGetProperty("steps", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.RunBatch(p0);
			}
		},
		["sbox_batch_delete"] = new StaticallyBoundTool
		{
			Name = "sbox_batch_delete",
			Description = "Delete multiple GameObjects by GUID. Takes a JSON array of GUID strings.",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				var p0 = el.TryGetProperty("guids", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.BatchDelete(p0);
			}
		},
		["sbox_batch_transform"] = new StaticallyBoundTool
		{
			Name = "sbox_batch_transform",
			Description = "Set transform on multiple GameObjects. Takes a JSON array of { id, x?, y?, z?, pitch?, yaw?, roll?, scale? }.",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				var p0 = el.TryGetProperty("transforms", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.BatchTransform(p0);
			}
		},
		["sbox_undo"] = new StaticallyBoundTool
		{
			Name = "sbox_undo",
			Description = "Undoes the last action.",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				return inst.Undo();
			}
		},
		["sbox_redo"] = new StaticallyBoundTool
		{
			Name = "sbox_redo",
			Description = "Redoes the last undone action.",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				return inst.Redo();
			}
		},
		["sbox_undo_history"] = new StaticallyBoundTool
		{
			Name = "sbox_undo_history",
			Description = "Lists all undo-able actions.",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				return inst.UndoHistory();
			}
		},
		["sbox_undo_clear"] = new StaticallyBoundTool
		{
			Name = "sbox_undo_clear",
			Description = "Clears all undo/redo history.",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				return inst.UndoClear();
			}
		},
		["sbox_config_set"] = new StaticallyBoundTool
		{
			Name = "sbox_config_set",
			Description = "Save a key-value pair to persistent storage. Values persist across sessions.",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				var p0 = el.TryGetProperty("key", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("value", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				return inst.ConfigSet(p0, p1);
			}
		},
		["sbox_config_get"] = new StaticallyBoundTool
		{
			Name = "sbox_config_get",
			Description = "Read a value from persistent storage by key.",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				var p0 = el.TryGetProperty("key", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.ConfigGet(p0);
			}
		},
		["sbox_config_list"] = new StaticallyBoundTool
		{
			Name = "sbox_config_list",
			Description = "List all stored configuration keys.",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				return inst.ConfigList();
			}
		},
		["sbox_config_delete"] = new StaticallyBoundTool
		{
			Name = "sbox_config_delete",
			Description = "Delete a stored configuration value by key.",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				var p0 = el.TryGetProperty("key", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.ConfigDelete(p0);
			}
		},
		["sbox_subscribe_event"] = new StaticallyBoundTool
		{
			Name = "sbox_subscribe_event",
			Description = "Subscribe to game events. Events: phase_change, day_change, alarm, quota_due",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				var p0 = el.TryGetProperty("eventType", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.SubscribeEvent(p0);
			}
		},
		["sbox_unsubscribe_event"] = new StaticallyBoundTool
		{
			Name = "sbox_unsubscribe_event",
			Description = "Unsubscribe from a game event.",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				var p0 = el.TryGetProperty("eventType", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.UnsubscribeEvent(p0);
			}
		},
		["sbox_search_assets"] = new StaticallyBoundTool
		{
			Name = "sbox_search_assets",
			Description = "Search for assets by type (prefab, model, material, sound, texture, animation) and name query.",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				var p0 = el.TryGetProperty("type", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("query", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				var p2 = el.TryGetProperty("maxResults", out var v2) ? JsonSerializer.Deserialize<int>(v2.GetRawText()) : default(int);
				return inst.SearchAssets(p0, p1, p2);
			}
		},
		["sbox_list_events"] = new StaticallyBoundTool
		{
			Name = "sbox_list_events",
			Description = "List all available game event types.",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				return inst.ListEvents();
			}
		},
		["sbox_dry_run"] = new StaticallyBoundTool
		{
			Name = "sbox_dry_run",
			Description = "Validate a tool call without executing it. Checks if tool exists and parses arguments.",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				var p0 = el.TryGetProperty("tool", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("paramsJson", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				return inst.DryRun(p0, p1);
			}
		},
		["sbox_read_logs"] = new StaticallyBoundTool
		{
			Name = "sbox_read_logs",
			Description = "Returns recent MCP tool log entries. Capture is manual — engine logs are not available (s&box Log has no hook API).",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				var p0 = el.TryGetProperty("count", out var v0) ? JsonSerializer.Deserialize<int>(v0.GetRawText()) : default(int);
				var p1 = el.TryGetProperty("enable", out var v1) ? JsonSerializer.Deserialize<bool>(v1.GetRawText()) : default(bool);
				return inst.ReadLogs(p0, p1);
			}
		},
		["sbox_export_scene"] = new StaticallyBoundTool
		{
			Name = "sbox_export_scene",
			Description = "Export entire scene hierarchy as JSON. Includes transforms, components, and children.",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				return inst.ExportScene();
			}
		},
		["sbox_import_scene"] = new StaticallyBoundTool
		{
			Name = "sbox_import_scene",
			Description = "Import scene hierarchy from JSON. Recreates GameObjects, transforms, components, and hierarchy.",
			Group = "Core",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.CoreTools();
				var p0 = el.TryGetProperty("sceneJson", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.ImportScene(p0);
			}
		},
		["sbox_debug_inspect"] = new StaticallyBoundTool
		{
			Name = "sbox_debug_inspect",
			Description = "Returns ALL properties and fields of a GameObject or Component by GUID and optional component index.",
			Group = "Debug",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.DebugTools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("componentIndex", out var v1) ? JsonSerializer.Deserialize<int>(v1.GetRawText()) : default(int);
				return inst.DebugInspect(p0, p1);
			}
		},
		["sbox_debug_stack"] = new StaticallyBoundTool
		{
			Name = "sbox_debug_stack",
			Description = "Returns current call stack info.",
			Group = "Debug",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.DebugTools();
				return inst.DebugStack();
			}
		},
		["sbox_debug_watch"] = new StaticallyBoundTool
		{
			Name = "sbox_debug_watch",
			Description = "Watch a GameObject by GUID for N seconds. Uses GameTask.Delay to avoid blocking.",
			Group = "Debug",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.DebugTools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("durationSeconds", out var v1) ? JsonSerializer.Deserialize<int>(v1.GetRawText()) : default(int);
				var p2 = el.TryGetProperty("intervalMs", out var v2) ? JsonSerializer.Deserialize<int>(v2.GetRawText()) : default(int);
				return inst.DebugWatch(p0, p1, p2);
			}
		},
		["sbox_debug_list_components"] = new StaticallyBoundTool
		{
			Name = "sbox_debug_list_components",
			Description = "Lists all component types available in the game.",
			Group = "Debug",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.DebugTools();
				var p0 = el.TryGetProperty("query", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.DebugListComponents(p0);
			}
		},
		["sbox_debug_type_info"] = new StaticallyBoundTool
		{
			Name = "sbox_debug_type_info",
			Description = "Lists all methods, properties, and fields of a TypeLibrary type. Use for API discovery.",
			Group = "Debug",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.DebugTools();
				var p0 = el.TryGetProperty("typeName", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.DebugTypeInfo(p0);
			}
		},
		["sbox_debug_search_types"] = new StaticallyBoundTool
		{
			Name = "sbox_debug_search_types",
			Description = "Search for registered types by name pattern. Useful for finding correct API types.",
			Group = "Debug",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.DebugTools();
				var p0 = el.TryGetProperty("query", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("category", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				return inst.DebugSearchTypes(p0, p1);
			}
		},
		["sbox_set_master_volume"] = new StaticallyBoundTool
		{
			Name = "sbox_set_master_volume",
			Description = "Set master volume (0.0 = silent, 1.0 = full).",
			Group = "Effects",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.EffectsTools();
				var p0 = el.TryGetProperty("volume", out var v0) ? JsonSerializer.Deserialize<float>(v0.GetRawText()) : default(float);
				return inst.SetMasterVolume(p0);
			}
		},
		["sbox_get_master_volume"] = new StaticallyBoundTool
		{
			Name = "sbox_get_master_volume",
			Description = "Returns current master volume level.",
			Group = "Effects",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.EffectsTools();
				return inst.GetMasterVolume();
			}
		},
		["sbox_emit_particle"] = new StaticallyBoundTool
		{
			Name = "sbox_emit_particle",
			Description = "Spawns a particle effect at a world position. Creates a temporary ParticleSystem component.",
			Group = "Effects",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.EffectsTools();
				var p0 = el.TryGetProperty("particleName", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("x", out var v1) ? JsonSerializer.Deserialize<float>(v1.GetRawText()) : default(float);
				var p2 = el.TryGetProperty("y", out var v2) ? JsonSerializer.Deserialize<float>(v2.GetRawText()) : default(float);
				var p3 = el.TryGetProperty("z", out var v3) ? JsonSerializer.Deserialize<float>(v3.GetRawText()) : default(float);
				var p4 = el.TryGetProperty("forwardX", out var v4) ? JsonSerializer.Deserialize<float>(v4.GetRawText()) : default(float);
				var p5 = el.TryGetProperty("forwardY", out var v5) ? JsonSerializer.Deserialize<float>(v5.GetRawText()) : default(float);
				var p6 = el.TryGetProperty("forwardZ", out var v6) ? JsonSerializer.Deserialize<float>(v6.GetRawText()) : default(float);
				return inst.EmitParticle(p0, p1, p2, p3, p4, p5, p6);
			}
		},
		["sbox_stop_particles"] = new StaticallyBoundTool
		{
			Name = "sbox_stop_particles",
			Description = "Stops all active particle effects.",
			Group = "Effects",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.EffectsTools();
				return inst.StopParticles();
			}
		},
		["sbox_find_carts"] = new StaticallyBoundTool
		{
			Name = "sbox_find_carts",
			Description = "Finds all cart GameObjects in the scene.",
			Group = "Game",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.GameTools();
				return inst.FindCarts();
			}
		},
		["sbox_get_cart_info"] = new StaticallyBoundTool
		{
			Name = "sbox_get_cart_info",
			Description = "Returns detailed info about a GameObject.",
			Group = "Game",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.GameTools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.GetCartInfo(p0);
			}
		},
		["sbox_spawn_cart"] = new StaticallyBoundTool
		{
			Name = "sbox_spawn_cart",
			Description = "Spawns a new GameObject at a position.",
			Group = "Game",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.GameTools();
				var p0 = el.TryGetProperty("x", out var v0) ? JsonSerializer.Deserialize<float>(v0.GetRawText()) : default(float);
				var p1 = el.TryGetProperty("y", out var v1) ? JsonSerializer.Deserialize<float>(v1.GetRawText()) : default(float);
				var p2 = el.TryGetProperty("z", out var v2) ? JsonSerializer.Deserialize<float>(v2.GetRawText()) : default(float);
				var p3 = el.TryGetProperty("name", out var v3) ? JsonSerializer.Deserialize<string>(v3.GetRawText()) : default(string);
				return inst.SpawnCart(p0, p1, p2, p3);
			}
		},
		["sbox_remove_gameobject"] = new StaticallyBoundTool
		{
			Name = "sbox_remove_gameobject",
			Description = "Removes a GameObject by GUID.",
			Group = "Game",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.GameTools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.RemoveGameObject(p0);
			}
		},
		["sbox_set_gameobject_position"] = new StaticallyBoundTool
		{
			Name = "sbox_set_gameobject_position",
			Description = "Sets the position of a GameObject.",
			Group = "Game",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.GameTools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("x", out var v1) ? JsonSerializer.Deserialize<float>(v1.GetRawText()) : default(float);
				var p2 = el.TryGetProperty("y", out var v2) ? JsonSerializer.Deserialize<float>(v2.GetRawText()) : default(float);
				var p3 = el.TryGetProperty("z", out var v3) ? JsonSerializer.Deserialize<float>(v3.GetRawText()) : default(float);
				return inst.SetPosition(p0, p1, p2, p3);
			}
		},
		["sbox_set_gameobject_rotation"] = new StaticallyBoundTool
		{
			Name = "sbox_set_gameobject_rotation",
			Description = "Sets the rotation (pitch,yaw,roll) of a GameObject.",
			Group = "Game",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.GameTools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("pitch", out var v1) ? JsonSerializer.Deserialize<float>(v1.GetRawText()) : default(float);
				var p2 = el.TryGetProperty("yaw", out var v2) ? JsonSerializer.Deserialize<float>(v2.GetRawText()) : default(float);
				var p3 = el.TryGetProperty("roll", out var v3) ? JsonSerializer.Deserialize<float>(v3.GetRawText()) : default(float);
				return inst.SetRotation(p0, p1, p2, p3);
			}
		},
		["sbox_set_sun_direction"] = new StaticallyBoundTool
		{
			Name = "sbox_set_sun_direction",
			Description = "Sets the DirectionalLight direction.",
			Group = "Game",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.GameTools();
				var p0 = el.TryGetProperty("pitch", out var v0) ? JsonSerializer.Deserialize<float>(v0.GetRawText()) : default(float);
				var p1 = el.TryGetProperty("yaw", out var v1) ? JsonSerializer.Deserialize<float>(v1.GetRawText()) : default(float);
				return inst.SetSunDirection(p0, p1);
			}
		},
		["sbox_list_macros"] = new StaticallyBoundTool
		{
			Name = "sbox_list_macros",
			Description = "Lists all saved macros.",
			Group = "Game",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.GameTools();
				return inst.ListMacros();
			}
		},
		["sbox_get_macro"] = new StaticallyBoundTool
		{
			Name = "sbox_get_macro",
			Description = "Gets a saved macro by name.",
			Group = "Game",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.GameTools();
				var p0 = el.TryGetProperty("name", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.GetMacro(p0);
			}
		},
		["sbox_save_macro"] = new StaticallyBoundTool
		{
			Name = "sbox_save_macro",
			Description = "Saves a macro (list of tool steps).",
			Group = "Game",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.GameTools();
				var p0 = el.TryGetProperty("name", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("description", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				return inst.SaveMacro(p0, p1);
			}
		},
		["sbox_delete_macro"] = new StaticallyBoundTool
		{
			Name = "sbox_delete_macro",
			Description = "Deletes a saved macro.",
			Group = "Game",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.GameTools();
				var p0 = el.TryGetProperty("name", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.DeleteMacro(p0);
			}
		},
		["sbox_list_snapshots"] = new StaticallyBoundTool
		{
			Name = "sbox_list_snapshots",
			Description = "Lists all saved scene snapshots.",
			Group = "Game",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.GameTools();
				return inst.ListSnapshots();
			}
		},
		["sbox_health"] = new StaticallyBoundTool
		{
			Name = "sbox_health",
			Description = "Returns health metrics for the MCP server.",
			Group = "Game",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.GameTools();
				return inst.Health();
			}
		},
		["sbox_metrics"] = new StaticallyBoundTool
		{
			Name = "sbox_metrics",
			Description = "Returns per-tool performance metrics.",
			Group = "Game",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.GameTools();
				return inst.Metrics();
			}
		},
		["sbox_clear_replay"] = new StaticallyBoundTool
		{
			Name = "sbox_clear_replay",
			Description = "Clears all replay history.",
			Group = "Game",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.GameTools();
				return inst.ClearReplay();
			}
		},
		["sbox_replay_playback"] = new StaticallyBoundTool
		{
			Name = "sbox_replay_playback",
			Description = "Starts replaying recorded commands.",
			Group = "Game",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.GameTools();
				return inst.ReplayPlayback();
			}
		},
		["sbox_hotload_trigger"] = new StaticallyBoundTool
		{
			Name = "sbox_hotload_trigger",
			Description = "Triggers a script hot-reload.",
			Group = "Hotload",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.HotloadTools();
				return inst.TriggerHotload();
			}
		},
		["sbox_hotload_status"] = new StaticallyBoundTool
		{
			Name = "sbox_hotload_status",
			Description = "Checks if hotload API is available and returns detected types.",
			Group = "Hotload",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.HotloadTools();
				return inst.HotloadStatus();
			}
		},
		["sbox_hotload_code"] = new StaticallyBoundTool
		{
			Name = "sbox_hotload_code",
			Description = "Writes a code snippet to a file and triggers hot-reload.",
			Group = "Hotload",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.HotloadTools();
				var p0 = el.TryGetProperty("fileName", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("code", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				return inst.WriteAndHotload(p0, p1);
			}
		},
		["sbox_play_sound"] = new StaticallyBoundTool
		{
			Name = "sbox_play_sound",
			Description = "Plays a sound at a position or on a GameObject.",
			Group = "Media",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.MediaTools();
				var p0 = el.TryGetProperty("soundEvent", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("x", out var v1) ? JsonSerializer.Deserialize<float>(v1.GetRawText()) : default(float);
				var p2 = el.TryGetProperty("y", out var v2) ? JsonSerializer.Deserialize<float>(v2.GetRawText()) : default(float);
				var p3 = el.TryGetProperty("z", out var v3) ? JsonSerializer.Deserialize<float>(v3.GetRawText()) : default(float);
				return inst.PlaySound(p0, p1, p2, p3);
			}
		},
		["sbox_stop_all_sounds"] = new StaticallyBoundTool
		{
			Name = "sbox_stop_all_sounds",
			Description = "Stops all playing sounds.",
			Group = "Media",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.MediaTools();
				return inst.StopAllSounds();
			}
		},
		["sbox_set_camera_fov"] = new StaticallyBoundTool
		{
			Name = "sbox_set_camera_fov",
			Description = "Changes the main camera field of view (10-170 degrees).",
			Group = "Media",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.MediaTools();
				var p0 = el.TryGetProperty("fov", out var v0) ? JsonSerializer.Deserialize<float>(v0.GetRawText()) : default(float);
				return inst.SetCameraFov(p0);
			}
		},
		["sbox_set_camera_position"] = new StaticallyBoundTool
		{
			Name = "sbox_set_camera_position",
			Description = "Moves the main camera to a position.",
			Group = "Media",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.MediaTools();
				var p0 = el.TryGetProperty("x", out var v0) ? JsonSerializer.Deserialize<float>(v0.GetRawText()) : default(float);
				var p1 = el.TryGetProperty("y", out var v1) ? JsonSerializer.Deserialize<float>(v1.GetRawText()) : default(float);
				var p2 = el.TryGetProperty("z", out var v2) ? JsonSerializer.Deserialize<float>(v2.GetRawText()) : default(float);
				return inst.SetCameraPosition(p0, p1, p2);
			}
		},
		["sbox_reset_camera"] = new StaticallyBoundTool
		{
			Name = "sbox_reset_camera",
			Description = "Resets the main camera to default position/rotation.",
			Group = "Media",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.MediaTools();
				return inst.ResetCamera();
			}
		},
		["sbox_set_gravity"] = new StaticallyBoundTool
		{
			Name = "sbox_set_gravity",
			Description = "Sets the scene's global gravity vector.",
			Group = "Physics",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.PhysicsTools();
				var p0 = el.TryGetProperty("x", out var v0) ? JsonSerializer.Deserialize<float>(v0.GetRawText()) : default(float);
				var p1 = el.TryGetProperty("y", out var v1) ? JsonSerializer.Deserialize<float>(v1.GetRawText()) : default(float);
				var p2 = el.TryGetProperty("z", out var v2) ? JsonSerializer.Deserialize<float>(v2.GetRawText()) : default(float);
				return inst.SetGravity(p0, p1, p2);
			}
		},
		["sbox_get_gravity"] = new StaticallyBoundTool
		{
			Name = "sbox_get_gravity",
			Description = "Returns the current global gravity vector.",
			Group = "Physics",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.PhysicsTools();
				return inst.GetGravity();
			}
		},
		["sbox_set_timescale"] = new StaticallyBoundTool
		{
			Name = "sbox_set_timescale",
			Description = "Sets the global time scale (1.0 = normal speed).",
			Group = "Physics",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.PhysicsTools();
				var p0 = el.TryGetProperty("scale", out var v0) ? JsonSerializer.Deserialize<float>(v0.GetRawText()) : default(float);
				return inst.SetTimescale(p0);
			}
		},
		["sbox_get_timescale"] = new StaticallyBoundTool
		{
			Name = "sbox_get_timescale",
			Description = "Returns the current global time scale.",
			Group = "Physics",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.PhysicsTools();
				return inst.GetTimescale();
			}
		},
		["sbox_get_velocity"] = new StaticallyBoundTool
		{
			Name = "sbox_get_velocity",
			Description = "Returns the velocity of a GameObject's Rigidbody.",
			Group = "Physics",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.PhysicsTools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.GetVelocity(p0);
			}
		},
		["sbox_overlap_sphere"] = new StaticallyBoundTool
		{
			Name = "sbox_overlap_sphere",
			Description = "Finds GameObjects with colliders in a sphere radius.",
			Group = "Physics",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.PhysicsTools();
				var p0 = el.TryGetProperty("cx", out var v0) ? JsonSerializer.Deserialize<float>(v0.GetRawText()) : default(float);
				var p1 = el.TryGetProperty("cy", out var v1) ? JsonSerializer.Deserialize<float>(v1.GetRawText()) : default(float);
				var p2 = el.TryGetProperty("cz", out var v2) ? JsonSerializer.Deserialize<float>(v2.GetRawText()) : default(float);
				var p3 = el.TryGetProperty("radius", out var v3) ? JsonSerializer.Deserialize<float>(v3.GetRawText()) : default(float);
				return inst.OverlapSphere(p0, p1, p2, p3);
			}
		},
		["sbox_get_physics_bodies"] = new StaticallyBoundTool
		{
			Name = "sbox_get_physics_bodies",
			Description = "Lists all GameObjects with a Rigidbody.",
			Group = "Physics",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.PhysicsTools();
				var p0 = el.TryGetProperty("filter", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.GetPhysicsBodies(p0);
			}
		},
		["sbox_set_physics_material"] = new StaticallyBoundTool
		{
			Name = "sbox_set_physics_material",
			Description = "Sets physics damping/mass on a Rigidbody.",
			Group = "Physics",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.PhysicsTools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("linearDamping", out var v1) ? JsonSerializer.Deserialize<float?>(v1.GetRawText()) : default(float?);
				var p2 = el.TryGetProperty("angularDamping", out var v2) ? JsonSerializer.Deserialize<float?>(v2.GetRawText()) : default(float?);
				var p3 = el.TryGetProperty("mass", out var v3) ? JsonSerializer.Deserialize<float?>(v3.GetRawText()) : default(float?);
				return inst.SetPhysicsMaterial(p0, p1, p2, p3);
			}
		},
		["sbox_add_force"] = new StaticallyBoundTool
		{
			Name = "sbox_add_force",
			Description = "Applies an impulse force to a Rigidbody.",
			Group = "Physics",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.PhysicsTools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("dx", out var v1) ? JsonSerializer.Deserialize<float>(v1.GetRawText()) : default(float);
				var p2 = el.TryGetProperty("dy", out var v2) ? JsonSerializer.Deserialize<float>(v2.GetRawText()) : default(float);
				var p3 = el.TryGetProperty("dz", out var v3) ? JsonSerializer.Deserialize<float>(v3.GetRawText()) : default(float);
				var p4 = el.TryGetProperty("magnitude", out var v4) ? JsonSerializer.Deserialize<float>(v4.GetRawText()) : default(float);
				return inst.AddForce(p0, p1, p2, p3, p4);
			}
		},
		["sbox_add_torque"] = new StaticallyBoundTool
		{
			Name = "sbox_add_torque",
			Description = "Applies angular impulse to a Rigidbody.",
			Group = "Physics",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.PhysicsTools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("tx", out var v1) ? JsonSerializer.Deserialize<float>(v1.GetRawText()) : default(float);
				var p2 = el.TryGetProperty("ty", out var v2) ? JsonSerializer.Deserialize<float>(v2.GetRawText()) : default(float);
				var p3 = el.TryGetProperty("tz", out var v3) ? JsonSerializer.Deserialize<float>(v3.GetRawText()) : default(float);
				return inst.AddTorque(p0, p1, p2, p3);
			}
		},
		["sbox_find_lights"] = new StaticallyBoundTool
		{
			Name = "sbox_find_lights",
			Description = "Lists all light components in the scene.",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				return inst.FindLights();
			}
		},
		["sbox_set_light_color"] = new StaticallyBoundTool
		{
			Name = "sbox_set_light_color",
			Description = "Sets color and optional properties on a light.",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("color", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				var p2 = el.TryGetProperty("shadows", out var v2) ? JsonSerializer.Deserialize<string>(v2.GetRawText()) : default(string);
				var p3 = el.TryGetProperty("shadowHardness", out var v3) ? JsonSerializer.Deserialize<string>(v3.GetRawText()) : default(string);
				var p4 = el.TryGetProperty("fogStrength", out var v4) ? JsonSerializer.Deserialize<string>(v4.GetRawText()) : default(string);
				return inst.SetLightColor(p0, p1, p2, p3, p4);
			}
		},
		["sbox_set_fog"] = new StaticallyBoundTool
		{
			Name = "sbox_set_fog",
			Description = "Controls fog settings on the scene's DirectionalLight.",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				var p0 = el.TryGetProperty("mode", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("strength", out var v1) ? JsonSerializer.Deserialize<float?>(v1.GetRawText()) : default(float?);
				var p2 = el.TryGetProperty("lightGuid", out var v2) ? JsonSerializer.Deserialize<string>(v2.GetRawText()) : default(string);
				return inst.SetFog(p0, p1, p2);
			}
		},
		["sbox_set_background"] = new StaticallyBoundTool
		{
			Name = "sbox_set_background",
			Description = "Changes the main camera background color.",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				var p0 = el.TryGetProperty("color", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("clearFlags", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				return inst.SetBackground(p0, p1);
			}
		},
		["sbox_set_exposure"] = new StaticallyBoundTool
		{
			Name = "sbox_set_exposure",
			Description = "Set camera exposure compensation (EV, range -6 to +6).",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				var p0 = el.TryGetProperty("ev100", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("autoExposure", out var v1) ? JsonSerializer.Deserialize<bool>(v1.GetRawText()) : default(bool);
				return inst.SetExposure(p0, p1);
			}
		},
		["sbox_set_shadow_settings"] = new StaticallyBoundTool
		{
			Name = "sbox_set_shadow_settings",
			Description = "Sets shadow quality settings on the main directional light.",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				var p0 = el.TryGetProperty("distance", out var v0) ? JsonSerializer.Deserialize<float?>(v0.GetRawText()) : default(float?);
				var p1 = el.TryGetProperty("bias", out var v1) ? JsonSerializer.Deserialize<float?>(v1.GetRawText()) : default(float?);
				var p2 = el.TryGetProperty("normalBias", out var v2) ? JsonSerializer.Deserialize<float?>(v2.GetRawText()) : default(float?);
				var p3 = el.TryGetProperty("cascadeCount", out var v3) ? JsonSerializer.Deserialize<int?>(v3.GetRawText()) : default(int?);
				var p4 = el.TryGetProperty("lightGuid", out var v4) ? JsonSerializer.Deserialize<string>(v4.GetRawText()) : default(string);
				return inst.SetShadowSettings(p0, p1, p2, p3, p4);
			}
		},
		["sbox_set_skybox"] = new StaticallyBoundTool
		{
			Name = "sbox_set_skybox",
			Description = "Creates or modifies a skybox. Auto-creates SkyBox2D if none exists.",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				var p0 = el.TryGetProperty("materialPath", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("intensity", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				return inst.SetSkybox(p0, p1);
			}
		},
		["sbox_set_tonemapping"] = new StaticallyBoundTool
		{
			Name = "sbox_set_tonemapping",
			Description = "Changes the tonemapping mode. Options: none, aces, reinhard, neutral, filmic.",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				var p0 = el.TryGetProperty("mode", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.SetTonemapping(p0);
			}
		},
		["sbox_set_post_process"] = new StaticallyBoundTool
		{
			Name = "sbox_set_post_process",
			Description = "Enables or disables post-processing on the main camera.",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				var p0 = el.TryGetProperty("enabled", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.SetPostProcess(p0);
			}
		},
		["sbox_set_tint"] = new StaticallyBoundTool
		{
			Name = "sbox_set_tint",
			Description = "Sets the tint color on a ModelRenderer.",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("color", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				return inst.SetTint(p0, p1);
			}
		},
		["sbox_set_material"] = new StaticallyBoundTool
		{
			Name = "sbox_set_material",
			Description = "Overrides the material on a ModelRenderer.",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("materialPath", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				return inst.SetMaterial(p0, p1);
			}
		},
		["sbox_reset_material"] = new StaticallyBoundTool
		{
			Name = "sbox_reset_material",
			Description = "Removes the material override.",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.ResetMaterial(p0);
			}
		},
		["sbox_add_logic_rule"] = new StaticallyBoundTool
		{
			Name = "sbox_add_logic_rule",
			Description = "Creates a new Logic Weaver rule.",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				var p0 = el.TryGetProperty("triggerType", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("sourceGuid", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				var p2 = el.TryGetProperty("actionType", out var v2) ? JsonSerializer.Deserialize<string>(v2.GetRawText()) : default(string);
				var p3 = el.TryGetProperty("targetGuid", out var v3) ? JsonSerializer.Deserialize<string>(v3.GetRawText()) : default(string);
				var p4 = el.TryGetProperty("actionParams", out var v4) ? JsonSerializer.Deserialize<string>(v4.GetRawText()) : default(string);
				return inst.AddLogicRule(p0, p1, p2, p3, p4);
			}
		},
		["sbox_remove_logic_rule"] = new StaticallyBoundTool
		{
			Name = "sbox_remove_logic_rule",
			Description = "Removes a Logic Weaver rule by ID.",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				var p0 = el.TryGetProperty("ruleId", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.RemoveLogicRule(p0);
			}
		},
		["sbox_list_logic_rules"] = new StaticallyBoundTool
		{
			Name = "sbox_list_logic_rules",
			Description = "Lists all Logic Weaver rules.",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				return inst.ListLogicRules();
			}
		},
		["sbox_clear_logic_rules"] = new StaticallyBoundTool
		{
			Name = "sbox_clear_logic_rules",
			Description = "Clears all Logic Weaver rules.",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				return inst.ClearLogicRules();
			}
		},
		["sbox_fire_logic_trigger"] = new StaticallyBoundTool
		{
			Name = "sbox_fire_logic_trigger",
			Description = "Fires a trigger event on the Logic Weaver rules.",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				var p0 = el.TryGetProperty("triggerType", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("sourceGuid", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				return inst.FireLogicTrigger(p0, p1);
			}
		},
		["sbox_navmesh_find_path"] = new StaticallyBoundTool
		{
			Name = "sbox_navmesh_find_path",
			Description = "Finds a path between two points on the navmesh.",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				var p0 = el.TryGetProperty("fx", out var v0) ? JsonSerializer.Deserialize<float>(v0.GetRawText()) : default(float);
				var p1 = el.TryGetProperty("fy", out var v1) ? JsonSerializer.Deserialize<float>(v1.GetRawText()) : default(float);
				var p2 = el.TryGetProperty("fz", out var v2) ? JsonSerializer.Deserialize<float>(v2.GetRawText()) : default(float);
				var p3 = el.TryGetProperty("tx", out var v3) ? JsonSerializer.Deserialize<float>(v3.GetRawText()) : default(float);
				var p4 = el.TryGetProperty("ty", out var v4) ? JsonSerializer.Deserialize<float>(v4.GetRawText()) : default(float);
				var p5 = el.TryGetProperty("tz", out var v5) ? JsonSerializer.Deserialize<float>(v5.GetRawText()) : default(float);
				return inst.NavMeshFindPath(p0, p1, p2, p3, p4, p5);
			}
		},
		["sbox_navmesh_status"] = new StaticallyBoundTool
		{
			Name = "sbox_navmesh_status",
			Description = "Returns navmesh availability.",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				return inst.NavMeshStatus();
			}
		},
		["sbox_navmesh_random_point"] = new StaticallyBoundTool
		{
			Name = "sbox_navmesh_random_point",
			Description = "Returns a random point on the navmesh.",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				var p0 = el.TryGetProperty("cx", out var v0) ? JsonSerializer.Deserialize<float>(v0.GetRawText()) : default(float);
				var p1 = el.TryGetProperty("cy", out var v1) ? JsonSerializer.Deserialize<float>(v1.GetRawText()) : default(float);
				var p2 = el.TryGetProperty("cz", out var v2) ? JsonSerializer.Deserialize<float>(v2.GetRawText()) : default(float);
				var p3 = el.TryGetProperty("radius", out var v3) ? JsonSerializer.Deserialize<float>(v3.GetRawText()) : default(float);
				return inst.NavMeshRandomPoint(p0, p1, p2, p3);
			}
		},
		["sbox_get_waypoint_graph"] = new StaticallyBoundTool
		{
			Name = "sbox_get_waypoint_graph",
			Description = "Generates a simplified weighted node graph of key interest points (shelves, checkout zones, spawners) in the scene connected by NavMesh path distances.",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				return inst.GetWaypointGraph();
			}
		},
		["sbox_set_wind"] = new StaticallyBoundTool
		{
			Name = "sbox_set_wind",
			Description = "Sets wind direction and speed. Note: WindComponent not available in this SDK version.",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				var p0 = el.TryGetProperty("directionX", out var v0) ? JsonSerializer.Deserialize<float>(v0.GetRawText()) : default(float);
				var p1 = el.TryGetProperty("directionY", out var v1) ? JsonSerializer.Deserialize<float>(v1.GetRawText()) : default(float);
				var p2 = el.TryGetProperty("directionZ", out var v2) ? JsonSerializer.Deserialize<float>(v2.GetRawText()) : default(float);
				var p3 = el.TryGetProperty("speed", out var v3) ? JsonSerializer.Deserialize<float>(v3.GetRawText()) : default(float);
				return inst.SetWind(p0, p1, p2, p3);
			}
		},
		["sbox_render_get_info"] = new StaticallyBoundTool
		{
			Name = "sbox_render_get_info",
			Description = "Returns render/display information: resolution, shadow settings, quality levels.",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				return inst.RenderGetInfo();
			}
		},
		["sbox_terrain_query"] = new StaticallyBoundTool
		{
			Name = "sbox_terrain_query",
			Description = "Queries terrain/ground height at a world position. Uses raycast downward.",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				var p0 = el.TryGetProperty("x", out var v0) ? JsonSerializer.Deserialize<float>(v0.GetRawText()) : default(float);
				var p1 = el.TryGetProperty("y", out var v1) ? JsonSerializer.Deserialize<float>(v1.GetRawText()) : default(float);
				return inst.TerrainQuery(p0, p1);
			}
		},
		["sbox_scene_settings"] = new StaticallyBoundTool
		{
			Name = "sbox_scene_settings",
			Description = "Read or modify scene-wide settings: fog, lighting, physics via reflection.",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				var p0 = el.TryGetProperty("fogColor", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("fogStart", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				var p2 = el.TryGetProperty("fogEnd", out var v2) ? JsonSerializer.Deserialize<string>(v2.GetRawText()) : default(string);
				var p3 = el.TryGetProperty("gravityX", out var v3) ? JsonSerializer.Deserialize<string>(v3.GetRawText()) : default(string);
				var p4 = el.TryGetProperty("gravityY", out var v4) ? JsonSerializer.Deserialize<string>(v4.GetRawText()) : default(string);
				var p5 = el.TryGetProperty("gravityZ", out var v5) ? JsonSerializer.Deserialize<string>(v5.GetRawText()) : default(string);
				return inst.SceneSettings(p0, p1, p2, p3, p4, p5);
			}
		},
		["sbox_capture_screenshot"] = new StaticallyBoundTool
		{
			Name = "sbox_capture_screenshot",
			Description = "Captures a screenshot of the active game view and returns it as a Base64-encoded PNG.",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				return inst.CaptureScreenshot();
			}
		},
		["sbox_spatial_query"] = new StaticallyBoundTool
		{
			Name = "sbox_spatial_query",
			Description = "Query physics colliders in the scene. Support box overlap (specify minX/minY/minZ and maxX/maxY/maxZ) or sphere overlap (specify centerX/centerY/centerZ and radius).",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				var p0 = el.TryGetProperty("minX", out var v0) ? JsonSerializer.Deserialize<float?>(v0.GetRawText()) : default(float?);
				var p1 = el.TryGetProperty("minY", out var v1) ? JsonSerializer.Deserialize<float?>(v1.GetRawText()) : default(float?);
				var p2 = el.TryGetProperty("minZ", out var v2) ? JsonSerializer.Deserialize<float?>(v2.GetRawText()) : default(float?);
				var p3 = el.TryGetProperty("maxX", out var v3) ? JsonSerializer.Deserialize<float?>(v3.GetRawText()) : default(float?);
				var p4 = el.TryGetProperty("maxY", out var v4) ? JsonSerializer.Deserialize<float?>(v4.GetRawText()) : default(float?);
				var p5 = el.TryGetProperty("maxZ", out var v5) ? JsonSerializer.Deserialize<float?>(v5.GetRawText()) : default(float?);
				var p6 = el.TryGetProperty("centerX", out var v6) ? JsonSerializer.Deserialize<float?>(v6.GetRawText()) : default(float?);
				var p7 = el.TryGetProperty("centerY", out var v7) ? JsonSerializer.Deserialize<float?>(v7.GetRawText()) : default(float?);
				var p8 = el.TryGetProperty("centerZ", out var v8) ? JsonSerializer.Deserialize<float?>(v8.GetRawText()) : default(float?);
				var p9 = el.TryGetProperty("radius", out var v9) ? JsonSerializer.Deserialize<float?>(v9.GetRawText()) : default(float?);
				return inst.SpatialQuery(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9);
			}
		},
		["sbox_rewind_state"] = new StaticallyBoundTool
		{
			Name = "sbox_rewind_state",
			Description = "Rewinds the game state (transforms of key objects and synced variables) to a specified number of seconds ago (max 60 seconds).",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				var p0 = el.TryGetProperty("secondsAgo", out var v0) ? JsonSerializer.Deserialize<float>(v0.GetRawText()) : default(float);
				return inst.RewindState(p0);
			}
		},
		["sbox_balance_simulation"] = new StaticallyBoundTool
		{
			Name = "sbox_balance_simulation",
			Description = "Starts a high-speed RL balance simulation with timescale adjustments and sub-stepping stability optimization.",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				var p0 = el.TryGetProperty("timeScale", out var v0) ? JsonSerializer.Deserialize<float>(v0.GetRawText()) : default(float);
				var p1 = el.TryGetProperty("simulationDuration", out var v1) ? JsonSerializer.Deserialize<float>(v1.GetRawText()) : default(float);
				var p2 = el.TryGetProperty("botCount", out var v2) ? JsonSerializer.Deserialize<int>(v2.GetRawText()) : default(int);
				return inst.BalanceSimulation(p0, p1, p2);
			}
		},
		["sbox_physics_raycast"] = new StaticallyBoundTool
		{
			Name = "sbox_physics_raycast",
			Description = "Performs a raycast in the physics world and returns hit details.",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				var p0 = el.TryGetProperty("originX", out var v0) ? JsonSerializer.Deserialize<float>(v0.GetRawText()) : default(float);
				var p1 = el.TryGetProperty("originY", out var v1) ? JsonSerializer.Deserialize<float>(v1.GetRawText()) : default(float);
				var p2 = el.TryGetProperty("originZ", out var v2) ? JsonSerializer.Deserialize<float>(v2.GetRawText()) : default(float);
				var p3 = el.TryGetProperty("dirX", out var v3) ? JsonSerializer.Deserialize<float>(v3.GetRawText()) : default(float);
				var p4 = el.TryGetProperty("dirY", out var v4) ? JsonSerializer.Deserialize<float>(v4.GetRawText()) : default(float);
				var p5 = el.TryGetProperty("dirZ", out var v5) ? JsonSerializer.Deserialize<float>(v5.GetRawText()) : default(float);
				return inst.PhysicsRaycast(p0, p1, p2, p3, p4, p5);
			}
		},
		["sbox_get_entity_metrics"] = new StaticallyBoundTool
		{
			Name = "sbox_get_entity_metrics",
			Description = "Gathers memory and execution metrics for active scene entities to detect performance leaks.",
			Group = "Scene",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.SceneTools();
				return inst.GetEntityMetrics();
			}
		},
		["sbox_list_files"] = new StaticallyBoundTool
		{
			Name = "sbox_list_files",
			Description = "Lists files in the game's data directory.",
			Group = "Server",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.ServerTools();
				var p0 = el.TryGetProperty("path", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.ListFiles(p0);
			}
		},
		["sbox_read_file"] = new StaticallyBoundTool
		{
			Name = "sbox_read_file",
			Description = "Reads file contents from the data directory.",
			Group = "Server",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.ServerTools();
				var p0 = el.TryGetProperty("filePath", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.ReadFile(p0);
			}
		},
		["sbox_write_file"] = new StaticallyBoundTool
		{
			Name = "sbox_write_file",
			Description = "Writes content to a file in the data directory. Only .json, .txt, .xml allowed.",
			Group = "Server",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.ServerTools();
				var p0 = el.TryGetProperty("filePath", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("content", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				return inst.WriteFile(p0, p1);
			}
		},
		["sbox_delete_file"] = new StaticallyBoundTool
		{
			Name = "sbox_delete_file",
			Description = "Deletes a file from the data directory.",
			Group = "Server",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.ServerTools();
				var p0 = el.TryGetProperty("filePath", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.DeleteFile(p0);
			}
		},
		["sbox_list_logs"] = new StaticallyBoundTool
		{
			Name = "sbox_list_logs",
			Description = "Retrieves recent engine log entries.",
			Group = "Server",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.ServerTools();
				var p0 = el.TryGetProperty("count", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				return inst.ListLogs(p0);
			}
		},
		["sbox_run_tests"] = new StaticallyBoundTool
		{
			Name = "sbox_run_tests",
			Description = "Run in-game tests",
			Group = "Test",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				return McpBridge.Tools.TestTools.RunTests();
			}
		},
		["sbox_ui_world_panel"] = new StaticallyBoundTool
		{
			Name = "sbox_ui_world_panel",
			Description = "Creates a WorldPanel on a GameObject. Renders a Razor UI in 3D space.",
			Group = "UI",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.UITools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("name", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				var p2 = el.TryGetProperty("width", out var v2) ? JsonSerializer.Deserialize<float>(v2.GetRawText()) : default(float);
				var p3 = el.TryGetProperty("height", out var v3) ? JsonSerializer.Deserialize<float>(v3.GetRawText()) : default(float);
				var p4 = el.TryGetProperty("razorPath", out var v4) ? JsonSerializer.Deserialize<string>(v4.GetRawText()) : default(string);
				return inst.CreateWorldPanel(p0, p1, p2, p3, p4);
			}
		},
		["sbox_ui_text_display"] = new StaticallyBoundTool
		{
			Name = "sbox_ui_text_display",
			Description = "Creates a TextDisplay on a GameObject. Shows text in 3D space.",
			Group = "UI",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.UITools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("name", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				var p2 = el.TryGetProperty("text", out var v2) ? JsonSerializer.Deserialize<string>(v2.GetRawText()) : default(string);
				var p3 = el.TryGetProperty("color", out var v3) ? JsonSerializer.Deserialize<string>(v3.GetRawText()) : default(string);
				var p4 = el.TryGetProperty("size", out var v4) ? JsonSerializer.Deserialize<float>(v4.GetRawText()) : default(float);
				return inst.CreateTextDisplay(p0, p1, p2, p3, p4);
			}
		},
		["sbox_ui_set_text"] = new StaticallyBoundTool
		{
			Name = "sbox_ui_set_text",
			Description = "Updates the text content of a TextDisplay component on a GameObject.",
			Group = "UI",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.UITools();
				var p0 = el.TryGetProperty("guidStr", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("text", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				return inst.SetText(p0, p1);
			}
		},
		["sbox_show_toast"] = new StaticallyBoundTool
		{
			Name = "sbox_show_toast",
			Description = "Displays a toast notification on the player's screen.",
			Group = "UI",
			ReadOnlyHint = false,
			DestructiveHint = false,
			Invoke = (el) =>
			{
				var inst = new McpBridge.Tools.UITools();
				var p0 = el.TryGetProperty("message", out var v0) ? JsonSerializer.Deserialize<string>(v0.GetRawText()) : default(string);
				var p1 = el.TryGetProperty("type", out var v1) ? JsonSerializer.Deserialize<string>(v1.GetRawText()) : default(string);
				var p2 = el.TryGetProperty("duration", out var v2) ? JsonSerializer.Deserialize<float>(v2.GetRawText()) : default(float);
				return inst.ShowToast(p0, p1, p2);
			}
		},
	};
}
